version: '3.8'

services:
  # 1. Database Service
  postgres-db:
    image: postgres:15-alpine
    container_name: ledger-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ledger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Node.js Application Service
  ledger-app:
    build: .
    container_name: ledger-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Dhyan dein: Yahan localhost ki jagah 'postgres-db' (container ka naam) use hua hai
      DATABASE_URL: "postgresql://admin:adminpassword@postgres-db:5432/ledger_db?schema=public"
    depends_on:
      - postgres-db

# Data persist karne ke liye volume (taaki Docker band hone pe DB ka data delete na ho)
volumes:
  postgres_data: